### PR TITLE
chore: configure vscode workspace

### PR DESCRIPTION
**Pull request by ExampleWasTaken**
*...this PR is 100% identical to #66. While re-structuring my branch setup I renamed the branch and didn't think of the fact that this would close the PR 😂*

## Description
This PR configures the VS Code workspace to ensure a correct environment setup.
It also adds recommendations for the ESLint and .editorconfig extensions as they greatly enhance the DX.

## Test Results
No code has been modified.

### CODE REVIEW

**Comment by pdellaert** [comment]
Probably need some check with other devs to see if they have an issue. I'll check this out myself as well

**Comment by ExampleWasTaken** [comment]
Yep, I'm totally open for suggestions, so far this is based on the settings we have in the aircraft repo.

**Comment by benw202** [comment]
All looks good to me, I don't use VS code but I'm happy with it if it's based off of the aircraft repo!

**Review by pdellaert — APPROVED** [review]

**Review by pdellaert — APPROVED** [review]

**Comment by ExampleWasTaken** [comment]
The project breaks with TS `v^5.5.x` due to a bug fix added in that version. VSCode, by default, uses the TS version it ships with, so we need to force it to use the version of the workspace (the one in node_modules).

see #78

**Review by benw202 — APPROVED** [review]

**Pull request merged**
